#!/usr/bin/env sh

set -e

kubesetup

if [ -z ${KUBE_ECR_SECRET_NAME} ]; then
    echo "Variable KUBE_ECR_SECRET_NAME is required!" > /dev/stderr
    exit 1
fi

if [ -z ${ECR_REGISTRY} ]; then
    echo "Variable ECR_REGISTRY is required!" > /dev/stderr
    exit 1
fi

ECR_PASSWORD=$(aws ecr get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d | cut -d: -f2)

kubectl delete "secret/${KUBE_ECR_SECRET_NAME}"
kubectl create secret docker-registry "${KUBE_ECR_SECRET_NAME}" \
    --docker-server="${ECR_REGISTRY}" \
    --docker-username=AWS \
    --docker-password="${ECR_PASSWORD}"
